/*
 * Netsoc webspaced
 *
 * API for managing next-gen webspaces. 
 *
 * API version: 1.1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package webspaced
// ImageAlias LXD image alias
type ImageAlias struct {
	Name string `json:"name,omitempty"`
	Description string `json:"description,omitempty"`
}
