/*
 * Netsoc webspaced
 *
 * API for managing next-gen webspaces. 
 *
 * API version: 1.1.2
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package webspaced
// ExecRequest struct for ExecRequest
type ExecRequest struct {
	Command string `json:"command"`
}
