/*
 * Netsoc webspaced
 *
 * API for managing next-gen webspaces. 
 *
 * API version: 1.2.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package webspaced
// ExecInteractiveRequest struct for ExecInteractiveRequest
type ExecInteractiveRequest struct {
	Command []string `json:"command"`
	// User ID to run as
	User int32 `json:"user,omitempty"`
	// Group ID to run as
	Group int32 `json:"group,omitempty"`
	// Additional environment variables to pass to process
	Environment map[string]string `json:"environment,omitempty"`
	// Width of terminal (columns)
	Width int32 `json:"width"`
	// Height of terminal (rows)
	Height int32 `json:"height"`
	WorkingDirectory string `json:"workingDirectory,omitempty"`
}
