/*
 * Netsoc webspaced
 *
 * API for managing next-gen webspaces. 
 *
 * API version: 1.0.2
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package webspaced
// State Webspace state
type State struct {
	Running bool `json:"running"`
	// Length of time for which container has been running (seconds)
	Uptime float32 `json:"uptime"`
	Usage Usage `json:"usage"`
	NetworkInterfaces map[string]NetworkInterface `json:"networkInterfaces"`
}
