/*
 * Netsoc webspaced
 *
 * API for managing next-gen webspaces. 
 *
 * API version: 1.1.2
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package webspaced
// ResizeRequest struct for ResizeRequest
type ResizeRequest struct {
	// Width of terminal (columns)
	Width int32 `json:"width"`
	// Height of terminal (rows)
	Height int32 `json:"height"`
}
