/*
 * Netsoc webspaced
 *
 * API for managing next-gen webspaces. 
 *
 * API version: 1.0.3
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package webspaced
// Error struct for Error
type Error struct {
	// Message explaining the error
	Message string `json:"message"`
}
