/*
 * Netsoc webspaced
 *
 * API for managing next-gen webspaces. 
 *
 * API version: 1.2.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package webspaced
// AddRandomPortResponse struct for AddRandomPortResponse
type AddRandomPortResponse struct {
	// Network port
	EPort int32 `json:"ePort"`
}
