log_level: TRACE
iam:
  url: 'https://iam.netsoc.ie/v1'
  token: A.B.C
  token_file: ''
  allow_insecure: false
lxd:
  url: https://localhost
  tls:
    ca:
    server_cert:
    client_cert:
    client_key:
    trust_password: hunter2
    allow_insecure: false
webspaces:
  lxd_profile: webspace
  instance_prefix: 'ws-'
  domain: ng.localhost
  config_defaults:
    startup_delay: 3
    http_port: 80
    sni_passthrough: false
  max_startup_delay: 60
  ip_timeout: '10s'
  ports:
    start: 49152
    end: 65535
    max: 64
    kubernetes_service: ''
http:
  listen_address: ':8080'
  cors:
    allowed_origins: ['*']
traefik:
  provider: kubernetes
  redis:
    addr: '127.0.0.1:6379'
    db: 0
    cert_resolver: ''
  kubernetes:
    namespace: webspace-ng
    default_secret: ''
    cluster_issuer: ''
  https_entrypoint: https
  default_sans: ['*.ng.localhost']
  webspaced_url: 'http://localhost:8080'
  iam_token: A.B.C
  iam_token_file: ''
