FROM golang:1.15-alpine
RUN apk --no-cache add git gcc musl-dev linux-headers

RUN install -d -m 777 /.cache
WORKDIR /usr/local/lib/webspaced
VOLUME /usr/local/lib/webspaced

COPY go.mod go.sum tools.go ./
RUN cat tools.go | sed -nr 's|^\t_ "(.+)"$|\1|p' | xargs -tI % go get %

COPY build.dev.sh /usr/local/bin/build.sh
CMD ["CompileDaemon", "-exclude-dir=.git", "-exclude-dir=data", \
    "-exclude-dir=internal/data", \
    "-build=build.sh", "-command=bin/webspaced", \
    "-graceful-kill"]
