FROM ghcr.io/netsoc/traefik AS traefik


FROM alpine:3.12
COPY --from=traefik /traefik /usr/local/bin/traefik

RUN apk --no-cache add redis

COPY traefik-entrypoint.sh /entrypoint.sh
ENTRYPOINT ["/entrypoint.sh"]
