FROM golang:1.13-alpine as builder
RUN apk --no-cache add gcc musl-dev

WORKDIR /usr/local/webspaced
COPY go.* ./
RUN go mod download

COPY . .
RUN go build -ldflags '-s -w' -o bin/ ./cmd/...


FROM alpine:3.11

COPY --from=builder /usr/local/webspaced/bin/* /usr/local/bin/

ENTRYPOINT ["/usr/local/bin/webspaced"]
