FROM netsoc/webspace-ng-traefik AS builder


FROM alpine:3.11
COPY --from=builder /traefik /usr/local/bin/traefik

RUN apk --no-cache add redis

COPY traefik-entrypoint.sh /entrypoint.sh
ENTRYPOINT ["/entrypoint.sh"]
