FROM golang:1.13-alpine
RUN apk --no-cache add git gcc musl-dev && go get github.com/githubnemo/CompileDaemon

WORKDIR /usr/local/webspaced

CMD ["CompileDaemon", "-exclude-dir=.git", "-build=go build -o bin/webspaced ./cmd/...", "-command=bin/webspaced", \
    "-graceful-kill"]
