FROM golang:1.15-alpine
RUN apk --no-cache add git gcc musl-dev linux-headers

RUN install -d -m 777 /.cache
WORKDIR /usr/local/lib/webspaced
VOLUME /usr/local/lib/webspaced

COPY tools.go ./
RUN cat tools.go | sed -nr 's|^\t_ "(.+)"$|\1|p' | xargs -tI % go get %

CMD ["CompileDaemon", "-exclude-dir=.git", "-build=go build -o bin/webspaced ./cmd/...", "-command=bin/webspaced", \
    "-graceful-kill"]
