apiVersion: v1
kind: Secret
metadata:
  name: {{ include "webspaced.fullname" . }}
  labels:
    {{- include "webspaced.labels" . | nindent 4 }}
data:
  {{- with .Values.secrets.iamToken }}
  iam_token.txt: {{ . | b64enc }}
  {{- end }}
  {{- with .Values.secrets.lxdKey }}
  lxd_client.key: {{ . | b64enc }}
  {{- end }}
  {{- with .Values.secrets.lxdTrust }}
  lxd_trust.txt: {{ . | b64enc | squote }}
  {{- end }}
  {{- with .Values.secrets.traefikIAMToken }}
  traefik_iam_token.txt: {{ . | b64enc }}
  {{- end }}
